CMake fails to build if `_DLL_VERSION` isn't set to something.
julianxhokaxhiu/FFNx pull request #258
Opened 2021-06-25 02:36 UTC by Sebanisu

added this to CMakeLists.txt
```cmake
if (NOT DEFINED _DLL_VERSION OR _DLL_VERSION MATCHES "")
    set(_DLL_VERSION "devel")
endif ()
```
and added this to .gitignore
```
# Clion
.idea/
cmake-build*/
```

2021-06-25 09:51 UTC, julianxhokaxhiu requested changes
Hey, thanks for the PR.

Actually that's on purpose and you should indeed create your own environment project file which sets that. For instance we have it done for [VS](https://github.com/julianxhokaxhiu/FFNx/blob/master/CMakeSettings.json#L11), [VSCode](https://github.com/julianxhokaxhiu/FFNx/blob/master/.vscode/settings.json#L5) and [CI](https://github.com/julianxhokaxhiu/FFNx/blob/master/.ci/build.ps1#L45) too.

If you want, please convert this PR into adding a CLion project file, I'll be happy to merge that!

Also fine by me to add the rules on the `.gitignore`, but please remove all the other files from the commit as they are all reindentation.

I'll try to add an `.editorconfig` to the repo so we can all be on the same side.

Thank you in advance,
Julian

2021-06-26 09:01 UTC, julianxhokaxhiu commented
Thanks, I find the PR to be more polished now and I like it.

I think you can also add the `.idea` folder too, which should be the project directory generated by CLion ( see https://www.jetbrains.com/help/clion/project.html#storage ). Keep the `.gitignore` rule anyway so we commit this directory once only with the required files to work and then we will not commit, or adapt it to ignore any other file but the ones required in this directory to work on CLion out of the box, up to you :)

2021-06-26 09:01 UTC, julianxhokaxhiu approved these changes

2021-06-26 09:17 UTC, Sebanisu commented
Okay I can add the .idea folder and I can squash. Though there is a squash and merge button on github. Though I work again today. So won't be able to change till tonight.

2021-06-26 09:34 UTC, julianxhokaxhiu commented
Here I merge things using only Rebase, and that's on purpose. Take your time though, there's no hurry :) Thanks!

2021-06-27 02:04 UTC, Sebanisu commented
I'll need to cherry pick the commits that are good. I get an error when i squash because i was merging your changes. And it said I can't rebase when i'm current. So I gotta cherry pick, and then rebase and then squash. I think. But I came home late so i have ran out of time. I work one more day then I'm off 2 days. Should get it done during that time.

2021-06-27 09:19 UTC, julianxhokaxhiu commented
As a personal suggestion in whichever project you work, never squash, always rebase. It will give you less headaches.

2021-06-28 02:34 UTC, Sebanisu commented
This should a similar effect as rebase. I cherry-picked the good commits and put those in a new branch. Then I hard reset this branch and squashed the cherry picked commits into this branch then merge them into this branch.

2021-06-30 15:30 UTC, julianxhokaxhiu approved these changes

2021-06-30 15:30 UTC, merged

2021-06-30 15:30 UTC, julianxhokaxhiu commented
Thank you!