FF7: Added experimental 16:10 support
julianxhokaxhiu/FFNx pull request #608
Opened 2023-09-26 20:47 UTC by dotaxis

## Summary

Crops 16:9 aspect ratio horizontally to support 16:10.

There may be a much better way to do this, but I wanted to at least have a discussion about it. Mod authors will need to add support for this if it reaches production.

### Motivation

The Steam Deck uses a resolution of 1280x800, and this will remove the black bars on the top and bottom of the screen.

### ACKs

- [x] I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file
- [x] I did test my code on FF7
- [ ] I did test my code on FF8

2023-09-26 21:34 UTC, julianxhokaxhiu commented
Thanks for this PR!

@CosmosXIII @tangtang95 can you please review?

2023-09-28 05:58 UTC, tangtang95 commented
It seems a good starting point. But please move the override of wide variables to the `Widescreen` init function and then move the call of `widescreen.init()` before `newRenderer.init()`. I think it might be better to have this logic into Widescreen class even though the renderer depends on these variables

Then there are also other global variables that could be overwritten in the `widescreen.cpp` file.

Overall I think it is ok for now

2023-09-28 14:24 UTC, dotaxis commented
If you are referring to these globals:
```
int viewport_width_plus_x_widescreen_fix = 750;
int swirl_framebuffer_offset_x_widescreen_fix = 106;
```
I don't really understand how these values are calculated. I thought that the first one might be `wide_viewport_width + wide_viewport_x + 3` and the second would be `-wide_viewport_x - 1` but I didn't want to just guess and give the impression that the new values were proper. Can you give some insight on that?

I will make the other changes you mentioned in the meantime.

2023-09-28 15:12 UTC, julianxhokaxhiu commented on src/ff7/widescreen.cpp
> +        wide_game_width = wide_16x10_game_width;
Can you please set the values directly instead of creating variables that are used only once in the entire code lifecycle?

2023-09-28 15:13 UTC, julianxhokaxhiu commented on misc/FFNx.toml
> +# 0: 16:9 aspect ratio
Please add a little description of what is this flag about. Thank you

2023-09-28 17:02 UTC, tangtang95 commented
@dotaxis I think that here https://github.com/julianxhokaxhiu/FFNx/blob/master/src/gl/special_case.cpp#L74C58-L74C58 we need to use a new variable that is the aspect ratio in float. By default it is `16/9.f`, but in your case, it should be `16/10.f`. Otherwise, external texture images in for `buster_tex` (background image of new game/continue menu) will be using a 16/9 image squashed into 16/10.

2023-09-28 17:20 UTC, dotaxis commented
Right. I did have something there in my initial draft but I forgot to fix it when I got ready for a PR. Will fix.

2023-09-28 17:37 UTC, tangtang95 commented
Ok, for me the PR is good now

2023-09-29 08:08 UTC, julianxhokaxhiu requested changes
I was looking more carefully at the PR and I'd like not to introduce another flag for controlling Widescreen. We already have `aspect_ratio` which is enough.

Therefore I propose the following changes:
- Remove `widescreen_ar` ( flag, toml section, etc. )
- Add a new option 3 for `aspect_ratio`
- Update the FFNx.toml to something like this:
```toml
#[ASPECT RATIO]
# Preserve original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
# When off the game will be stretched to fit the window's aspect ratio; Be aware the game may look wrong though.
# 0: Preserves original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
# 1: Stretched to fit the window's aspect ratio
# 2: 16:9 aspect ratio mode without stretching the image
# 3: 16:10 aspect ratio mode without stretching the image
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
aspect_ratio = 0
```
- Update the constant `AR_WIDESCREEN` to `AR_WIDESCREEN_16x9`
- Add a new constant `AR_WIDESCREEN_16x10`
- Use this constant as a discriminator in the new if condition where 16:10 values are set

This will keep the code cleaner, scalable and more robust, as well as simplify the addition of this option on 7th later.

Thank you in advance

2023-09-29 09:04 UTC, tangtang95 commented
> I was looking more carefully at the PR and I'd like not to introduce another flag for controlling Widescreen. We already have `aspect_ratio` which is enough.
> 
> Therefore I propose the following changes:
> - Remove `widescreen_ar` ( flag, toml section, etc. )
> - Add a new option 3 for `aspect_ratio`
> - Update the FFNx.toml to something like this:
> ```toml
> #[ASPECT RATIO]
> # Preserve original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
> # When off the game will be stretched to fit the window's aspect ratio; Be aware the game may look wrong though.
> # 0: Preserves original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
> # 1: Stretched to fit the window's aspect ratio
> # 2: 16:9 aspect ratio mode without stretching the image
> # 3: 16:10 aspect ratio mode without stretching the image
> #~~~~~~~~~~~~~~~~~~~~~~~~~~~
> aspect_ratio = 0
> ```
> - Update the constant `AR_WIDESCREEN` to `AR_WIDESCREEN_16x9`
> - Add a new constant `AR_WIDESCREEN_16x10`
> - Use this constant as a discriminator in the new if condition where 16:10 values are set
> 
> This will keep the code cleaner, scalable and more robust, as well as simplify the addition of this option on 7th later.
> 
> Thank you in advance

I think this was the previous solution proposed in Discord, but this required to change also all the if statement where `aspect_ratio == AR_WIDESCREEN` was used. I suggested to create a new flag in order to avoid modifying all those if statements. It wasn't really scalable in case another aspect ratio will be implemented (e.g 21:9, but this won't happen as it would be incompatible)

2023-09-29 14:52 UTC, dotaxis commented
> I think this was the previous solution proposed in Discord, but this required to change also all the if statement where `aspect_ratio == AR_WIDESCREEN` was used. I suggested to create a new flag in order to avoid modifying all those if statements. It wasn't really scalable in case another aspect ratio will be implemented (e.g 21:9, but this won't happen as it would be incompatible)

Yeah, I think the current solution is much cleaner than having a fourth aspect ratio because of the way FFNx handles 16:9 (many different checks to the value of `aspect_ratio` throughout the codebase).

However, it may work to use a `bool widescreen_enabled = (aspect_ratio >= AR_WIDESCREEN_16X9 && aspect_ratio < AR_COUNT)` and replacing all the `aspect_ratio` checks with `if (widescreen_enabled)` or similar.

That said, I think this is not really scalable either way since 16:10 is pretty much the only other widescreen resolution that we can reasonably support.

I can try out the changes suggested by @julianxhokaxhiu, but I'm not sure if the end result is actually going to be cleaner than this. I'll try.

2023-09-29 16:19 UTC, dotaxis commented
I have come up with what I believe is an acceptable, scalable solution. Please review.

2023-09-29 19:58 UTC, julianxhokaxhiu approved these changes
Allright, the PR LGTM to me :) Thanks @dotaxis!

@tangtang95 @CosmosXIII if you can have a final look I'd appreciate. By looking at the code I can't notice any particular drawback, on the opposite site the code can scale accommodating even new ARs eventually. Any drawbacks I can't see?

2023-09-29 20:29 UTC, tangtang95 commented
Yeah, seems good to me. In this way, it will be simpler for user and also if we want to extends 7th graphics driver config

2023-09-29 20:32 UTC, tangtang95 commented
> I have come up with what I believe is an acceptable, scalable solution. Please review.
> 
> The only caveat here is that mods that read aspect_ratio from the toml will think the game is running at 4:3 until they are updated. This may actually be better than the previous solution because now UI elements aren't getting cut off the edges of the screen.

It's better like this, so mods will have to be updated in order to support 16:10.
Anyway, nice work overall! 🎉

2023-09-29 20:48 UTC, dotaxis commented
@julianxhokaxhiu shouldn't this be a `bool`?
https://github.com/julianxhokaxhiu/FFNx/blob/e7aef843257ce2c6b56b4a7f3ada20f3b960fa05/src/globals.h#L69

2023-09-29 21:08 UTC, merged

2023-09-29 21:08 UTC, dotaxis commented
> > Edit: Maybe not, but I'm wondering what the reason for the type change is.
> 
> The bool type is anyway an integer in memory, and it uses 4 bytes. The current type will allow us to scale this flag eventually to a third or forth state in the future if needed :)
That makes sense. Thanks for explaining.

And thank you both for helping me get this up to spec!